### ISSUE TITLE
Memory limit is too restrictive - every possible binaries showing same info.. looks like there is some other issue.

### ISSUE THREAD

**Issue by rohith-krishnan** [GJDuck/e9afl#7]
$ afl-fuzz -m 850 -i input/ -o output/ -- ./test_binary.afl
afl-fuzz 2.52b by <lcamtuf@google.com>
[+] You have 8 CPU cores and 2 runnable tasks (utilization: 25%).
[+] Try parallel jobs - see /usr/share/doc/afl-doc/docs/parallel_fuzzing.txt.
[*] Checking CPU core loadout...
[+] Found a free CPU core, binding to #0.
[*] Checking core_pattern...
[*] Checking CPU scaling governor...
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning 'input/'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Validating target binary...
[*] Attempting dry run with 'id:000000,orig:exe'...
[*] Spinning up the fork server...

[-] Whoops, the target binary crashed suddenly, before receiving any input
    from the fuzzer! There are several probable explanations:

    - The current memory limit (850 MB) is too restrictive, causing the
      target to hit an OOM condition in the dynamic linker. Try bumping up
      the limit with the -m setting in the command line. A simple way confirm
      this diagnosis would be:

      ( ulimit -Sv $[849 << 10]; /path/to/fuzzed_app )

      Tip: you can use http://jwilk.net/software/recidivm to quickly
      estimate the required amount of virtual memory for the binary.

    - The binary is just buggy and explodes entirely on its own. If so, you
      need to fix the underlying problem or find a better replacement.

    - Less likely, there is a horrible bug in the fuzzer. If other options
      fail, poke <lcamtuf@coredump.cx> for troubleshooting tips.

[-] PROGRAM ABORT : Fork server crashed with signal 11
         Location : init_forkserver(), afl-fuzz.c:2201

**Comment by GJDuck** [comment]
Do the instrumented binaries run normally without `afl-fuzz`?

**Comment by rohith-krishnan** [comment]
Yes, it works fine without afl-fuzz.

**Comment by rohith-krishnan** [comment]
afl-fuzz worked with **-m none** option. 
afl-fuzz -i input/ -o output/ -m none -- ./esif_ufd.afl -a @@

Thanks.

**Comment by GJDuck** [comment]
It is probably just the memory limit issue.  E9AFL is based on the E9Patch static binary rewriting system, and E9Patch emits binaries that consume large amounts of virtual address space (although actual physical memory usage is proportional to the binary file size).  This seems to mess with AFL's virtual address space limits, which are imposed in order to detect oversized allocation bugs.  A similar problem exists when combining [AFL wth ASAN](https://afl-1.readthedocs.io/en/latest/notes_for_asan.html):

*afl-fuzz tries to protect you from processes that go off-rails and start consuming all the available memory in a vain attempt to parse a malformed input file.*

Rather than using `-m none`, there should be some finite limit (larger than 850) that will also work.
